### ISSUE TITLE
Awesome!  Also, another idea

### ISSUE THREAD

**Issue by matthewreeve** [srlabs/black-basta-buster#1]
First off, I would like to say: Great job!  :+1:

Also, if I squint a bit, this defective scheme looks a lot like reusing the same one-time pad over and over again.  It doesn't matter that the reused "OTP" was produced by XChaCha20, it could have just as easily been produced by fair dice roll.  So, maybe that's another possible angle of attack that could be used to recover information from files that don't happen to be susceptible to the known-plaintext attack.

**Comment by muelli** [comment]
Thanks for your feedback :)
And thanks for the pointer towards the source of the key material.
If you have any more insights, that you want to share, I'd be happy to be received emails encrypted under any of the keys to be found here: https://github.com/muelli.gpg
